// Generated by CoffeeScript 1.8.0
var app, config, express, ignore, moment, path, port, redirects, rewrites, _ref;

require('coffee-script');

require('coffee-script/register');

require('culoare');

express = require('express');

path = require('path');

moment = require('moment');

_ref = require('./config'), rewrites = _ref.rewrites, redirects = _ref.redirects, ignore = _ref.ignore, config = _ref.config;

app = express();

app.use(function(req, res, next) {
  if (!ignore.test(req.url)) {
    return next();
  }
  return res.redirect('/' + req.url.replace(ignore, ''));
});

app.use(function(req, res, next) {
  if (!redirects[req.url]) {
    return next();
  }
  return res.redirect(redirects[req.url]);
});

app.use(function(req, res, next) {
  if (!rewrites[req.url]) {
    return next();
  }
  req.url = rewrites[req.url];
  return next();
});

app.use(function(req, res, next) {
  var base;
  if (!/\.([a-z0-9]{1,5})$/i.test(req.url)) {
    console.error(req.url.green, moment().format().lightblue);
    base = req.url.replace(/\/$/, '');
    if (!/^curl/.test(req.headers['user-agent'])) {
      req.url = base + '.html';
    } else {
      req.url = base + '.md';
    }
  }
  return next();
});

app.use(express["static"](config["public"]));

app.use(express["static"](config["static"]));

app.use(function(req, res, next) {
  console.log('not found', req.url, req.headers['user-agent']);
  return next();
});

port = process.env.PORT || 7000;

app.listen(port);

console.log('listening at port', port);
