// Generated by CoffeeScript 1.9.3
(function() {
  var app, config, express, ignore, moment, path, port, redirects, ref, rewrites;

  require('coffee-script');

  require('coffee-script/register');

  require('culoare');

  express = require('express');

  path = require('path');

  moment = require('moment');

  ref = require('./config'), rewrites = ref.rewrites, redirects = ref.redirects, ignore = ref.ignore, config = ref.config;

  app = express();

  app.post('/canvas.md', function(req, res) {
    return res.send('I got this: ' + JSON.stringify(req.query));
  });

  app.use(function(req, res, next) {
    if (!ignore.test(req.url)) {
      return next();
    }
    return res.redirect('/' + req.url.replace(ignore, ''));
  });

  app.use(function(req, res, next) {
    if (!redirects[req.url]) {
      return next();
    }
    return res.redirect(redirects[req.url]);
  });

  app.use(function(req, res, next) {
    if (!rewrites[req.url]) {
      return next();
    }
    req.url = rewrites[req.url];
    return next();
  });

  app.use(function(req, res, next) {
    var base;
    if (!/\.([a-z0-9]{1,5})$/i.test(req.url)) {
      console.error(req.url.green, moment().format().lightblue);
      base = req.url.replace(/\/$/, '');
      if (!/^curl/.test(req.headers['user-agent'])) {
        req.url = base + '.html';
      } else {
        req.url = base + '.md';
      }
    }
    return next();
  });

  app.use(express["static"](config["public"]));

  app.use(express["static"](config["static"]));

  app.use(function(req, res, next) {
    console.log('not found', req.url, req.headers['user-agent']);
    return next();
  });

  port = process.env.PORT || 7000;

  app.listen(port);

  console.log('listening at port', port);

}).call(this);
